handle empty value returned by gerrit api
if gerrit retuns empty value, just use the info provided by the
gerrit plugin ($GERRIT_* env varibales) and checkout the current
change -- and don't try to get parent commit info.

projects like 'backup' are configured to disallow anonymous reads.
for such projects the api will return empty value

Change-Id: Ie38f913407b5ecbb7aad5871d950262465a1fe79
Reviewed-on: http://review.couchbase.org/61300
Reviewed-by: Will Gardner <will.gardner@couchbase.com>
Tested-by: Hari Kodungallur <hari.kodungallur@couchbase.com>

diff --git a/scripts/jenkins/commit_validation/single-project-clang-static-analyzer b/scripts/jenkins/commit_validation/single-project-clang-static-analyzer
--- a/scripts/jenkins/commit_validation/single-project-clang-static-analyzer
+++ b/scripts/jenkins/commit_validation/single-project-clang-static-analyzer
@@ -30,6 +30,10 @@ if [ -z "$GERRIT_REFSPEC" ]; then
     echo "Error: Required environment variable 'GERRIT_REFSPEC' not set."
     exit 5
 fi
+if [ -z "$GERRIT_CHANGE_ID" ]; then
+    echo "Error: Required environment variable 'GERRIT_CHANGE_ID' not set."
+    exit 6
+fi
 
 # Optional env vars - how many jobs to run in parallel by default?
 PARALLELISM="${PARALLELISM:-8}"
@@ -69,7 +73,7 @@ cat <<EOF
 ===          the same Change-Id          ===
 ============================================
 EOF
-${BASEDIR}/checkout_dependencies.py $GERRIT_PATCHSET_REVISION $GERRIT_PROJECT $GERRIT_REFSPEC
+${BASEDIR}/checkout_dependencies.py $GERRIT_PATCHSET_REVISION $GERRIT_CHANGE_ID $GERRIT_PROJECT $GERRIT_REFSPEC
 
 cat <<EOF
 
