Always checkout the refspec given
In some edge cases the refspec given will not be valid
for the manifest we're using (i.e. uses the wrong branch).In this
case we should just use it anyway.

Also checks that at least one change has been found and adds further
error checking to fetch_project.sh and fetch_project.bat in case of
an empty line.

Change-Id: I220bec846c05fe353f57c6c60ac2cf41f4aefa05
Reviewed-on: http://review.couchbase.org/60494
Tested-by: Will Gardner <will.gardner@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>

diff --git a/scripts/jenkins/commit_validation/single-project-gerrit b/scripts/jenkins/commit_validation/single-project-gerrit
--- a/scripts/jenkins/commit_validation/single-project-gerrit
+++ b/scripts/jenkins/commit_validation/single-project-gerrit
@@ -25,6 +25,10 @@ if [ -z "$GERRIT_PATCHSET_REVISION" ]; then
     echo "Error: Required environment variable 'GERRIT_PATCHSET_REVISION' not set."
     exit 4
 fi
+if [ -z "$GERRIT_REFSPEC" ]; then
+    echo "Error: Required environment variable 'GERRIT_REFSPEC' not set."
+    exit 5
+fi
 # Optional env vars - how many jobs to run in parallel by default?
 PARALLELISM="${PARALLELISM:-8}"
 TEST_PARALLELISM="${TEST_PARALLELISM:-${PARALLELISM}}"
@@ -97,7 +101,8 @@ cat <<EOF
 ===          the same Change-Id          ===
 ============================================
 EOF
-${BASEDIR}/alldependencies.py $GERRIT_PATCHSET_REVISION | xargs -n 3 ${BASEDIR}/fetch_project.sh
+${BASEDIR}/alldependencies.py $GERRIT_PATCHSET_REVISION $GERRIT_PROJECT $GERRIT_REFSPEC \
+ | xargs -n 3 ${BASEDIR}/fetch_project.sh
 
 cat <<EOF
 
