MB-27533 [8]: Update CBNT script to allow for differences in Master and CV runs
Change-Id: Id9ab91984e5036582b0c720e4a1fac42f514cb44
Reviewed-on: http://review.couchbase.org/89093
Reviewed-by: Dave Rigby <daver@couchbase.com>
Tested-by: Tim Bradgate <tim.bradgate@couchbase.com>

diff --git a/scripts/jenkins/commit_validation/single-project-cbnt b/scripts/jenkins/commit_validation/single-project-cbnt
--- a/scripts/jenkins/commit_validation/single-project-cbnt
+++ b/scripts/jenkins/commit_validation/single-project-cbnt
@@ -34,9 +34,17 @@ if [ -z "$LNT_IP" ]; then
     echo "Error: Required environment variable 'LNT_IP' not set."
     exit 8
 fi
-if [ "${GERRIT_PROJECT}" != "kv_engine" ]; then
-    echo "Error: Project ${GERRIT_PROJECT} is not kv_engine"
+if [ -z "$CBNT_TYPE" ]; then
+    echo "Error: Required environment variable 'CBNT_TYPE' not set."
     exit 9
+fi
+if [ -z "$ITERATIONS" ]; then
+    echo "Error: Required environment variable 'ITERATIONS' not set."
+    exit 10
+fi
+if [ "${GERRIT_PROJECT}" != "kv_engine" ]; then
+    echo "Error: Project ${GERRIT_PROJECT} is not kv_engine."
+    exit 11
 fi
 
 cd ${GERRIT_PROJECT}
@@ -57,4 +65,4 @@ cd ../..
 # we found this to be the most stable way of running the tests to get repeatable
 # results.
 numactl --interleave=all lnt runtest kv-engine ${WORKSPACE}/kv_engine/tests/cbnt_tests/cbnt_test_list.yml\
- cv --submit_url=http://${LNT_IP}/submitRun -v --commit=1
+ ${CBNT_TYPE} --submit_url=http://${LNT_IP}/submitRun -v --commit=1 --iterations=${ITERATIONS}
